name: Post Blog to LinkedIn

on:
  push:
    branches: [main]

jobs:
  post-to-linkedin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install node-fetch@2
      - name: Post new blog posts to LinkedIn
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        run: node scripts/postToLinkedIn.js 